### ISSUE TITLE
No rows gets selected

### ISSUE THREAD

**Issue by renepardon** [cpjolicoeur/mojo-database#2]
Hi,

i followed your instructions but no rows will be returned.

The following line results in SQLITE_DONE and no rows are fetched.
while (sqlite3_step(statement) == SQLITE_ROW) {

My setup looks like:

// Model:
@interface Genre : MojoModel
@property (nonatomic, retain) NSString\* name;
@end
@implementation Genre
@synthesize name=_name;
@end

// App delegate:
    self.myDatabase = [[AppDatabase alloc] initWithMigrations];
# ifdef TARGET_IPHONE_SIMULATOR

```
[self.myDatabase setLogging:YES];
```
# endif

// App database:
[self createGenreTable];
-(void)createGenreTable
{
    [self executeSql:@"CREATE  TABLE `main`.`Genre` (`primaryKey` INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , `name` VARCHAR);"];
}

There are already two rows within this table.
I tried fetching them with custom sql and with [Genre findAll];

best regards
René

**Comment by renepardon** [comment]
It was my mistake - have used the wrong table to insert test data ;)
Now it's working fine!

**Comment by cpjolicoeur** [comment]
I believe your issue is probably the namespacing/schema of your table creation.    

MojoDatabase currently only operates on non-namespaced tables.  So for a model named Genre, it is expecting a corresponding table named 'Genre' in the database. You are creating your table as `main.Genre` which MojoDatabase wouldn't be configured to look for.  

---

Craig P Jolicoeur
craig@craigpj.com
